name: antmaze_medium_play

obs_dim: 29 # 9*2 keypoints + 2 state
action_dim: 8



dataset:
  _target_: diffusion_policy.dataset.antmaze_lowdim_dataset.AntMazeLowdimDataset
  zarr_path: data/antmaze_medium_play_replay.zarr
  horizon: 16
  pad_before: 1
  pad_after: 1
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  obs_key: state
  action_key: action
